name: Testing

on: [push, workflow_dispatch]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: ["3.8"]

    steps:
    - uses: actions/checkout@v4
    - name: Set up Python ${{ matrix.python-version }}
      uses: actions/setup-python@v4
      with:
        python-version: ${{ matrix.python-version }}
    - name: Add conda to system path
      run: |
        # $CONDA is an environment variable pointing to the root of the miniconda directory
        echo $CONDA/bin >> $GITHUB_PATH
    - name: Install dependencies
      run: |
        conda env update --file environment.yml --name base
    - name: Test with pytest
      run: |
        # pytest test_get_oceancolor.py --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
        # pytest --doctest-modules --junitxml=junit/test-results-${{ matrix.python-version }}.xml
        # took out --doctest-modules b/c it was executing get_oceancolor.py
        pytest -v --durations=0 --junitxml=junit/test-results-${{ matrix.python-version }}.xml --cov=src --cov-report term-missing
    - name: Upload pytest test results
      uses: actions/upload-artifact@v3
      if: always()
      with:
        name: pytest-results-${{ matrix.python-version }}
        path: junit/test-results-${{ matrix.python-version }}.xml
